services:
  - type: web
    name: group-order-system
    env: node
    buildCommand: npm install
    startCommand: node src/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false # Will be set manually in Render dashboard
      - key: SESSION_SECRET
        sync: false # Will be set manually in Render dashboard